steps:
  # Build the container image - bunnytest is the name of project
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/bunnytest', '.']
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/bunnytest']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'deploy',  'bunnytest', '--image', 'gcr.io/$PROJECT_ID/bunnytest',  '--region', 'us-central1', '--platform', 'managed',
           '--allow-unauthenticated']
images:
  - 'gcr.io/$PROJECT_ID/bunnytest'